apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: color-app
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        configmap-update-hash: "{{ .Values.colorConfigMap | sha256sum }}"  # Exemple pour forcer le redéploiement
    spec:
      containers:
      - name: color-app
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: color-config
