apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: color-app
spec:
  replicas:   1
  selector:  # Le sélecteur est défini ici
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:  # Les labels doivent correspondre aux sélecteurs
        app: color-app
      annotations:
        configmap-update-hash: "{{ .Values.colorConfigMap | sha256sum }}"
    spec:
      containers:
      - name: color-app
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: color-config
