apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
  namespace: color-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html  # Monte le fichier index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: color-config  # Utilise le ConfigMap créé précédemment
