apiVersion: v1
kind: Service
metadata:
  name: color-app
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001  # Utilise ce port pour accéder à l'application
  selector:
    app: color-app
